FROM node:22-bookworm-slim AS deps
WORKDIR /app

RUN mkdir -p apps/web \
  libs/mopidy \
  libs/feature \
  libs/shared \
  libs/ui

COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY libs/mopidy/package.json ./libs/mopidy/package.json
COPY libs/feature/package.json ./libs/feature/package.json
COPY libs/shared/package.json ./libs/shared/package.json
COPY libs/ui/package.json ./libs/ui/package.json

RUN npm ci

FROM node:22-bookworm-slim AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build -w apps/web

FROM scratch AS artifact
COPY --from=builder /app/apps/web/.next/standalone /standalone
