# For information about configuration values that can be set in this file see:
#
#   https://docs.mopidy.com/en/latest/config/
#
# Run `sudo mopidyctl config` to see the current effective config, based on
# both defaults and this configuration file.

[core]  
cache_dir = /var/cache/mopidy  
data_dir = /var/lib/mopidy  
  
[audio]  
#output = alsasink device=hw:1,0
output = alsasink device=plughw:CARD=Audio,DEV=0
  
[http]  
enabled = true  
hostname = 0.0.0.0  
port = 6680  
  
[tidal]  
enabled = true  
quality = HI_RES_LOSSLESS
login_method = AUTO
auth_method = OAUTH
lazy = false
